//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 RoboMapping.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_STATUS_PANE3                124
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_RoboMappingTYPE             130
#define ID_WINDOW_MANAGER               131
#define IDD_GOTO_DLG                    134
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDC_DEL                         310
#define IDC_DEL_RECT                    311
#define IDD_TRANSFORM                   312
#define IDD_DIALOG1                     315
#define IDD_WAIT_BUSY                   315
#define IDD_TRANSLATION                 316
#define IDC_TRANSLATION                 317
#define IDC_REFLECTOR                   320
#define IDC_REFLECTOR2                  321
#define IDC_TRANSLATION2                322
#define IDC_ROTATE1                     323
#define IDC_ROTATE2                     324
#define IDC_ROTATE3                     325
#define IDC_DEL_THIS                    326
#define IDD_POINT_FEATURE               327
#define IDD_LINE_FEATURE                328
#define IDD_OUTPUT_OPTION               329
#define IDD_SAVE_DATASET_OPTION         329
#define IDD_EXPORT_OPTION               330
#define IDB_BITMAP1                     338
#define IDB_ROBOT                       338
#define IDB_BITMAP2                     339
#define IDC_CURSOR1                     340
#define IDC_REFLECTOR_MOVE              340
#define IDC_DEL_W                       341
#define IDD_REF_CREATE_PARAM            341
#define IDC_DEL_RECT_W                  342
#define IDC_DEL_THIS_W                  343
#define IDD_LINE_CREATE_PARAM           343
#define IDC_SEL_W                       345
#define IDC_SEL_THIS_W                  346
#define IDC_CURSOR2                     347
#define IDC_SEL_RECT_W                  347
#define IDD_OPTION                      348
#define IDD_LINK_DATASET_DLG            349
#define IDD_SCANNER_PARAM_DLG           352
#define IDD_WORLD_POINT                 355
#define IDC_X                           1000
#define IDC_ID                          1000
#define IDC_Y                           1001
#define IDC_POINT_X                     1001
#define IDC_THITA                       1002
#define IDC_POINT_Y                     1002
#define IDC_X2                          1003
#define IDC_Y2                          1004
#define IDC_X1                          1005
#define IDC_Y1                          1006
#define IDC_USE_REFLECTORS              1007
#define IDC_USE_LINES                   1008
#define IDC_SAVE_ALL                    1009
#define IDC_SAVE_PARTs                  1010
#define IDC_FROM                        1011
#define IDC_EDIT2                       1012
#define IDC_TO                          1012
#define IDC_NOTE                        1012
#define IDC_REF_INTENSITY_GATE          1013
#define IDC_REF_MAX_SIZE                1014
#define IDC_EDIT5                       1014
#define IDC_REF_MAX_RADIUS_VARIANCE     1015
#define IDC_MAX_P2P_DIST                1016
#define IDC_REF_MAX_RADIUS_VARIANCE2    1016
#define IDC_MIN_DIST_BETWEEN_REF        1016
#define IDC_MAX_P2L_DIST                1017
#define IDC_MAX_SIGMA                   1018
#define IDC_MIN_POINTS                  1019
#define IDC_STEP                        1020
#define IDC_MIN_LINE_LEN                1020
#define IDC_EDIT4                       1020
#define IDC_MIN_SCAN_ANGLE              1021
#define IDC_MIN_SCAN_ANGLE2             1022
#define IDC_MAX_LINE_MERGE_DIST         1022
#define IDC_MAP_RANGE_X                 1023
#define IDC_MAP_RANGE_Y                 1024
#define IDC_CELL_RESO                   1025
#define IDC_DATASET_MERGED              1026
#define IDC_BROWSE                      1027
#define ID_LINK                         1028
#define ID                              1028
#define IDC_INSTALL_X                   1028
#define IDC_CHECK1                      1029
#define IDC_REVERSE_ORDER               1029
#define IDC_INSTALL_Y                   1029
#define IDC_INSTALL_THITA               1030
#define IDC_VISIBLE_STAART_ANGLE        1031
#define IDC_VISIBLE_END_ANGLE           1032
#define IDC_COMBO1                      1034
#define IDC_SCANNER                     1034
#define IDC_USE_WHEN_CREATE_MODEL       1035
#define IDC_USE_WHEN_LOCALIZE           1036
#define IDC_EDIT1                       1037
#define IDC_INSTALL_Y1                  1037
#define IDC_EDIT_REL_TIME               1037
#define IDC_EDIT3                       1038
#define IDC_EDIT_REL_DATE               1038
#define IDC_EDIT7                       1039
#define IDC_EDIT_VERSION                1039
#define IDC_EDIT6                       1040
#define IDC_INSTALL_Y5                  1040
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SHOW_REFLECTORS              32771
#define ID_SHOW_LINES                   32772
#define ID_MAGNIFY                      32773
#define ID_REDUCE                       32774
#define ID_AUTO_FIT                     32775
#define ID_SAVE_MAP                     32776
#define ID_LOAD_MAP                     32776
#define ID_END_BUILD                    32777
#define ID_DEL_SINGLE                   32778
#define ID_DEL_RECT                     32779
#define ID_SHOW_SCENE                   32780
#define ID_TRANSFORM                    32781
#define ID_SHOW_ID                      32782
#define ID_VIEW_SCAN                    32784
#define ID_LOAD_DATASET                 32785
#define ID_SAVE_DATASET                 32786
#define ID_CONNECT_ROBOT                32787
#define ID_ROBOT_IP_ADDR                32789
#define ID_MAKE_MODEL                   32790
#define ID_PREV                         32791
#define ID_STEP_PREVIEW                 32792
#define ID_QUICK_BUILD                  32793
#define ID_PROGRESS                     32794
#define ID_SAVE_MAP2                    32795
#define IDC_STEP_COUNT                  32796
#define ID_TRANSLATION                  32798
#define ID_SHOW_ACTIVE_SIDE             32799
#define ID_MERGE                        32801
#define ID_PATCH_TRANSLATE              32802
#define ID_PATCH_ROTATE                 32804
#define ID_ACCEPT_MERGE                 32805
#define ID_CANCEL_MERGE                 32806
#define ID_ADD_LINE                     32806
#define ID_CHECK3                       32809
#define ID_SCAN_VIEW_LINES              32809
#define ID_MODEL_SHOW_HIGH_INTENSITY    32809
#define ID_ADD_REFLECTOR                32810
#define ID_SAVE_USER_EDIT_DATA          32812
#define ID_VIEW_PREV_STEP               32813
#define ID_VIEW_CUR_STEP                32814
#define ID_VIEW_CUR                     32815
#define ID_VIEW_SPECIFIED_STEP          32816
#define ID_TOGGLE_OBJ                   32817
#define ID_TOGGLE_AREA                  32818
#define ID_STEP_CONFIRM                 32819
#define ID_STEP_BUILD                   32820
#define ID_VIEW_ANY_STEP                32821
#define ID_REF_FEATURE_PARAM            32822
#define ID_LINE_FEATURE_PARAM           32823
#define ID_UNSELECT_ALL                 32825
#define ID_MARK_ALL_LINE                32826
#define ID_SELECT_ALL                   32827
#define ID_BUTTON6                      32828
#define ID_UNMARK_ALL_LINE              32828
#define ID_REMOVE_REFLECTOR             32828
#define ID_                             32829
#define ID_SCAN_COMPARE                 32829
#define ID_SHOW_TRANSFORMED             32831
#define ID_TRANSFORMED_SCAN             32831
#define ID_SCAN_VIEW_POINTS             32832
#define ID_SCAN_VIEW_POINT_FEATURES     32832
#define ID_AUTO_SELECT                  32833
#define ID_SELECT_SUGGESTED             32835
#define ID_LOCALIZE                     32836
#define ID_MAP_PARAM                    32837
#define ID_OFFSET_TEST                  32838
#define ID_PATCH_FIT                    32839
#define ID_SET_TRANS                    32840
#define ID_LINK_DATASET                 32841
#define ID_SCANNER_PARAM                32842
#define ID_SCANNERS_PARAM               32842
#define ID_CHECK2                       32843
#define ID_TARGET_MATCHED               32843
#define ID_RESET                        32844
#define ID_PREPARE_LOC                  32844
#define ID_BUTTON2                      32845
#define ID_LOC_INIT_POSTURE_TRANS       32845
#define ID_LOC_DATASET                  32845
#define ID_LOC_INIT_POSTURE_ROT         32846
#define ID_BATCH_LOCALIZE               32847
#define ID_VIEW_NEXT_STEP               32848
#define ID_BUTTON3                      32849
#define ID_LOCATE_DATASET               32849
#define ID_END_LOC                      32849
#define ID_END_LOCALIZE                 32850
#define ID_BUTTON4                      32851
#define ID_DATASET_FILTER               32851
#define ID_SCAN_SHOW_HIGH_INTENSITY     32853
#define ID_MODEL_SHOW_REFLECTORS        32854
#define ID_BUTTON5                      32855
#define ID_SCAN_COMP                    32855
#define ID_MODEL_USE_SCANNER_1          32856
#define ID_LOCALIZE_USE_SCANNER_1       32860
#define ID_CHECK11                      32863
#define ID_MODEL_USE_SCANNER_2          32864
#define ID_MODEL_USE_SCANNER_3          32865
#define ID_MODEL_USE_SCANNER_4          32866
#define ID_LOCALIZE_USE_SCANNER_2       32867
#define ID_LOCALIZE_USE_SCANNER_3       32868
#define ID_LOCALIZE_USE_SCANNER_4       32869
#define ID_BUTTON7                      32870
#define ID_IMPORT_ROUTE_MAP             32870

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        357
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
